name = "twentyfour-worker"
main = "src/index.ts"
compatibility_date = "2025-09-01"

# === D1 ===
[[d1_databases]]
binding = "DB"
database_name = "new24"                     # 必须是 new24
database_id = "af3404de-ea2c-4ddb-aefd-8cb7695fc80c"

# === KV ===
[[kv_namespaces]]
binding = "DAILY_KV"
id = "06c300ed6078420e994c248036848a49"

# === Durable Objects (bindings) ===
[[durable_objects.bindings]]
name = "ROOM_DO"
class_name = "RoomDO"

[[durable_objects.bindings]]
name = "SESSION_DO"
class_name = "SessionDO"

[[durable_objects.bindings]]
name = "LEADERBOARD_DO"
class_name = "LeaderboardDO"

# === CRON ===
[triggers]
crons = ["0 0 * * *"]

# === Durable Objects Migrations（首次必须加，免费版要用 SQLite 语法）===
[[migrations]]
tag = "v1"
new_sqlite_classes = [ "RoomDO", "SessionDO", "LeaderboardDO" ]

