name = "twentyfour-worker"
main = "src/index.ts"
compatibility_date = "2025-09-01"

[[d1_databases]]
binding = "DB"
database_name = "twentyfour-db"
database_id = "REPLACE_WITH_YOUR_D1_ID"

[[kv_namespaces]]
binding = "DAILY_KV"
id = "REPLACE_WITH_YOUR_KV_ID"

[[durable_objects.bindings]]
name = "ROOM_DO"
class_name = "RoomDO"

[[durable_objects.bindings]]
name = "SESSION_DO"
class_name = "SessionDO"

[[durable_objects.bindings]]
name = "LEADERBOARD_DO"
class_name = "LeaderboardDO"

[triggers]
crons = ["0 0 * * *"]
